name: Build Vendor

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist

      - name: Commit vendor back to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add vendor
          git commit -m "update vendor" || echo "no changes"
          git push
